# Generated by Django 6.0.1 on 2026-02-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('posts', '0002_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomerUser',
        ),
    ]
